name: Run Postman Collection

on:
  workflow_dispatch:

jobs:
  run-collection:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3  # Atualizado para a versão mais recente
        with:
          node-version: '16'  # Altere para 16 ou uma versão superior

      - name: Install Newman
        run: npm install -g newman newman-reporter-html

      - name: Run Postman Collection
        run: |
          newman run SimplesDental/SimplesDental.postman_collection.json \
          --reporters cli,html \
          --reporter-html-export newman-report.html

      - name: Upload Report
        uses: actions/upload-artifact@v3
        with:
          name: newman-report
          path: newman-report.html
