name: Run Postman Collection

on:
  workflow_dispatch:

jobs:
  run-collection:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.5.0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Newman and HTML Extra Reporter
        run: npm install -g newman newman-reporter-html newman-reporter-htmlextra

      - name: Create Results Directory
        run: mkdir -p testResults

      - name: Run Postman Collection
        run: |
          newman run SimplesDental.postman_collection.json \
          -r htmlextra --reporter-htmlextra-export ./testResults/htmlreport.html

      - name: Move Report to Repository
        run: |
          mkdir -p reports  # Cria a pasta "reports" no repositório
          mv ./testResults/htmlreport.html ./reports/htmlreport.html

      - name: Commit and Push Report
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          git add reports/htmlreport.html
          git commit -m "Add Postman collection report" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/wanpedroso0/SimplesDental.git HEAD:main

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
